num_dit_blocks: 6
num_convnext_blocks: 0

num_wavenet_blocks: 8
wavenet_kernel_size: 3
wavenet_dilation_cycle: 4
wavenet_skip_channels: 512
wavenet_dropout: 0.10

phoneme_blur_enabled: false
phoneme_blend_fraction: 0.2

use_plbert: true

# Generator speaker embedding
use_speaker_embedding: true
speaker_embedding_dim: 192
global_speaker_embedding_path: "../SpeakerEmbedding/embeddings/Rachie/speaker_embedding.pt"
